//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit > Rendering > Generate Shader Includes ] instead
//

#ifndef DEBUGMARKERS_CS_HLSL
#define DEBUGMARKERS_CS_HLSL
//
// Rukhanka.RukhankaDebugMarkers:  static fields
//
#define RUKHANKADEBUGMARKERS_DEFORMATION_COPY_MESH_DATA (0)
#define RUKHANKADEBUGMARKERS_DEFORMATION_COPY_BLEND_SHAPES (1)
#define RUKHANKADEBUGMARKERS_DEFORMATION_CREATE_PER_VERTEX_DEFORMATION_WORKLOAD (2)
#define RUKHANKADEBUGMARKERS_DEFORMATION_SKINNED_MESH_VERTEX_WRITE (3)
#define RUKHANKADEBUGMARKERS_DEFORMATION_SKINNED_MESH_VERTEX_READ (4)
#define RUKHANKADEBUGMARKERS_DEFORMATION_DEFORMED_VERTEX_READ (5)
#define RUKHANKADEBUGMARKERS_DEFORMATION_BONE_INFLUENCE_READ (6)
#define RUKHANKADEBUGMARKERS_DEFORMATION_DEFORMED_VERTEX_WRITE (7)
#define RUKHANKADEBUGMARKERS_DEFORMATION_FRAME_SKIN_MATRICES_READ (8)
#define RUKHANKADEBUGMARKERS_DEFORMATION_PER_VERTEX_WORKLOAD_READ (9)
#define RUKHANKADEBUGMARKERS_DEFORMATION_FRAME_DEFORMED_VERTEX_READ (10)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_MAKE_RIG_SPACE_BONE_TRANSFORMS_ANIMATED_BONE_WORKLOAD_READ (11)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_MAKE_RIG_SPACE_BONE_TRANSFORMS_ANIMATION_JOBS_READ (12)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_MAKE_RIG_SPACE_BONE_TRANSFORMS_BONE_LOCAL_TRANSFORMS_READ0 (13)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_MAKE_RIG_SPACE_BONE_TRANSFORMS_BONE_LOCAL_TRANSFORMS_READ1 (14)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_MAKE_RIG_SPACE_BONE_TRANSFORMS_OUT_BONE_TRANSFORMS_WRITE (15)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_COMPUTE_SKIN_MATRICES_SKIN_MATRIX_WORKLOAD_READ (16)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_COMPUTE_SKIN_MATRICES_RIG_SPACE_BONE_TRANSFORMS_READ (17)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_COMPUTE_SKIN_MATRICES_OUT_SKIN_MATRICES_WRITE (18)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_PROCESS_ANIMATIONS_ANIMATED_BONE_WORKLOAD_READ (19)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_PROCESS_ANIMATIONS_ANIMATION_JOBS_READ (20)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_PROCESS_ANIMATIONS_OUT_ANIMATED_BONES_WRITE (21)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_GENERIC_AVATAR_AVATAR_MASK_BUFFER_READ (22)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_HUMANOID_AVATAR_AVATAR_MASK_BUFFER_READ (23)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_HUMAN_ROTATION_DATA_READ (24)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_QUERY_PERFECT_HASH_TABLE_ANIMATION_CLIPS_READ0 (25)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_QUERY_PERFECT_HASH_TABLE_ANIMATION_CLIPS_READ1 (26)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_KEY_FRAME_READ (27)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_TRACK_READ (28)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_TRACK_SET_READ (29)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_ANIMATION_CLIP_READ (30)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_SKINNED_MESH_BONE_READ (31)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_RIG_DEFINITION_READ (32)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_RIG_BONE_READ (33)
#define RUKHANKADEBUGMARKERS_GPUANIMATOR_GPUATTACHMENT_RIG_SPACE_BONE_TRANSFORMS_READ (34)
#define RUKHANKADEBUGMARKERS_TOTAL (35)


#endif
